name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Get wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
          
      - name: wasm-pack build
        run: wasm-pack build
        
      - name: npm install
        run: npm install
        working-directory: ./www
        
      - name: npm run build
        run: npm build
        working-directory: ./www
        
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: ./www/dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
